### ISSUE TITLE
Create notifications

### ISSUE THREAD

**Issue by stevepopovich** [gm3dmo/the-power#127]
**Is your feature request related to a problem? Please describe.**

On Mobile, Notifications are a major flow for us. To be able to easily test that they work on GHES, I would love to have a way to populate notifications manually. Is there a way to do this or is an API missing? I am pretty new to this repo so don't feel comfortable tackling it myself, but if you point me in the right direction, I would be happy to try and tackle this.

**Describe the solution you'd like**

`build-all.sh` should populate 4-5 notifications. There should be a `create-notifications.sh` script. 

**Additional context**

This screen, for reference: 
![Screenshot_1702077504](https://github.com/gm3dmo/the-power/assets/3252375/03ab59b9-afad-4a65-9b52-8a772e441fc6)

**Comment by gm3dmo** [comment]
@stevepopovich the Notifications API:

https://docs.github.com/en/enterprise-cloud@latest/rest/activity/notifications?apiVersion=2022-11-28

at the current time only has get type endpoints for fetching information about notifications. I don't think it's possible to create a notification directly. Instead the user must create events like mention in a pull request which lead to a notification of some kind.

**Comment by stevepopovich** [comment]
Thanks for getting back to me. Darn it, I figured as much. It would be a bit weird for the API to have a way to artifically generate notificactions. All good, I'll look for workarounds for now.
