### ISSUE TITLE
tiny-app-create-check-run.sh actually creates a commit status, not a check run

### ISSUE THREAD

**Issue by mokshadharma** [gm3dmo/the-power#166]
**Describe the bug**

**To Reproduce**
1. `tiny-app-create-check-run.sh`
2. a commit status gets created

**Expected behavior**
It should create a check run

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.6.1
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**

**Additional context**
N/A

**Comment by gm3dmo** [comment]
The script isn't use by anything else:

```grep  tiny-app-create-check-run.sh *
grep: __pycache__: Is a directory
grep: docs: Is a directory
grep: extras: Is a directory
grep: hurl-tests: Is a directory
grep: make-n-commits: Is a directory
grep: src: Is a directory
grep: test-data: Is a directory
grep: tests: Is a directory
grep: tmp: Is a directory
```

The script `tiny-create-check-run.sh` is the correct one.

I'm going to remove `tiny-app-create-check-run.sh` to solve this.
