### ISSUE TITLE
Feature request: Allow create-pull-request.sh to create pull requests when one already exists.

### ISSUE THREAD

**Issue by mokshadharma** [gm3dmo/the-power#175]
**Is your feature request related to a problem? Please describe.**
I ran `./create-pull-request.sh` after a `./build-testcase` and got this error:

```
%  ./create-pull-request.sh
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequest",
      "code": "custom",
      "message": "A pull request already exists for yoyodyne-corporation:new_branch."
    }
  ],
  "documentation_url": "https://docs.github.com/rest/pulls/pulls#create-a-pull-request",
  "status": "422"
}
curl: (22) The requested URL returned error: 422
```

Then I tried passing a new pull request number as an argument to `create-pull-request.sh` by running:

```
./create-pull-request.sh 3
```

But that gave the same error.

**Describe the solution you'd like**
I'd like `./create-pull-request.sh` to create a new pull request, even if one already exists.

**Describe alternatives you've considered**
I could delete the existing pull request and try again, or I could hack the source code of `./create-pull-request.sh` myself, or do this myself using `curl`, but none of those seem like satisfactory, scalable, long-term solutions.

**Additional context**
N/A

**Comment by gm3dmo** [comment]
@mokshadharma you would need to create a new branch and target that for the pull request.

**Comment by gm3dmo** [comment]
These are the two variables the power scripts work with:

```
branch_name="new_branch"
protected_branch_name="main"
```

I'm going to close this as expected behaviour.
