### ISSUE TITLE
Evaluate removing the tiny app's dependency on ruby and replace it with python3 if possible

### ISSUE THREAD

**Issue by gm3dmo** [gm3dmo/the-power#62]
Ruby and it's jwt gem are needed for the jwt generation. If this doesn't need a python module then we could replace ruby with python for the jwt. If it needs a pip install then don't.

**Comment by gm3dmo** [comment]
looks like a pip install is needed for `jwt` https://github.com/auth0-blog/jwts-in-python

**Comment by kyanny** [comment]
I have reviewed https://jwt.io/libraries but it tells us that regardless of the choice of the programming language we need to install additional module/package to generate JWT.

If we really want to reduce the external dependency, we may use a shell script like this:
https://gist.github.com/briceburg/0d6589714862004609daf77f4fc4aac9
