### ISSUE TITLE
Add support for version header to the power

### ISSUE THREAD

**Issue by jjkennedy3** [gm3dmo/the-power#64]
With the new API structure supporting `X-GitHub-API-Version` header, some of the API calls are failing. Add support for a standard version `latest` and a way to override it.

**Comment by gm3dmo** [comment]
In: https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28 (no space)

<img width="773" alt="image" src="https://user-images.githubusercontent.com/4660778/210240809-9eb8988c-a3fe-4c64-9876-5ed8d810ecf8.png">

The presence or not of the space seems to affect the quoting when submitting with curl:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/4660778/210240645-de928ac6-d400-47f6-b9aa-a1bdc247be98.png">

**Comment by gm3dmo** [comment]
Can be set in:

```
### GitHub API Version
# https://docs.github.com/en/rest/overview/api-versions
github_api_version=2022-11-28
```
