### ISSUE TITLE
base64: invalid argument test-data/python/pip/requirements.txt_

### ISSUE THREAD

**Issue by mokshadharma** [gm3dmo/the-power#77]
**Describe the bug**
During a run of `bash build-all.sh` I got an error:

```
+ ./create-commit-python-pip.sh
base64: invalid argument test-data/python/pip/requirements.txt_
Usage:  base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

**To Reproduce**
1. Download and untar https://github.com/gm3dmo/the-power/archive/refs/tags/1.0.173.tar.gz
2. In #support-ops, type `.gheboot 3.7`
3. Log in to the appliance and manually create a PAT with all permissions
4. Run 'python3 configure.py' and answer the questions, paste in your token etc.
5. Run 'bash build-all.sh'
6. Get the base64 error pasted above

**Expected behavior**
No error.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Browser: Chrome 
 - Version 108.0.5359.124

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by mokshadharma** [comment]
It might be a good idea to use `set -e` in every script to force bash to break on error.

Otherwise even if it encounters an error, bash could continue on as if nothing happened.

**Comment by gm3dmo** [comment]
@mokshadharma see this https://github.com/gm3dmo/the-power/issues/70 for some backstory on the base64 thing.
